services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - wpnet
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/nginx/certs:/etc/ssl/private

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    restart: on-failure
    networks:
      - wpnet
    volumes:
      - wp_files:/var/www/html
    
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    restart: on-failure
    networks:
      - wpnet
    volumes:
      - wp_db:/var/lib/mysql

volumes:
  wp_db:
  wp_files:

networks:
  wpnet:
